name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI_BobApp"]
    branches: [ "main", "develop" ]
    types:
      - completed
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build_front:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./front
        run: npm install

      - name: Build Angular app
        working-directory: ./front
        run: npm run build

      - name: Build and tag Front Docker image
        working-directory: ./front
        run: docker build -t bobapp-front .

      - name: Login to Docker Hub
        if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag and push Front image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker tag bobapp-front ju49om/bobapp-front:$IMAGE_TAG
          docker push ju49om/bobapp-front:$IMAGE_TAG

  build_back:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Setup Java 11
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build Back-end
        working-directory: ./back
        run: mvn clean package -DskipTests

      - name: Build Back Docker image
        working-directory: ./back
        run: docker build -t bobapp-back .

      - name: Login to Docker Hub
        if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag and push Back image
        if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker tag bobapp-back ju49om/bobapp-back:$IMAGE_TAG
          docker push ju49om/bobapp-back:$IMAGE_TAG








