name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI_BobApp"]
    branches: [ "main", "develop" ]
    types: [ completed ]

jobs:
  build_front:
    name: Build Front (validation)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./front
        run: npm ci

      - name: Build Angular app
        working-directory: ./front
        run: npm run build

  build_back:
    name: Build Back (validation)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Java 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Build Back-end
        working-directory: ./back
        run: mvn -B clean package -DskipTests

  push_images:
    name: push Docker Images
    runs-on: ubuntu-latest
    needs: [ build_front, build_back ]

    if: ${{ success() && && github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}

    steps:
      - uses: actions/checkout@v5

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Front Docker image
        working-directory: ./front
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ju49om/bobapp-front:$IMAGE_TAG .
          docker push ju49om/bobapp-front:$IMAGE_TAG

      - name: Build & Push Back Docker image
        working-directory: ./back
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ju49om/bobapp-back:$IMAGE_TAG .
          docker push ju49om/bobapp-back:$IMAGE_TAG
