name: CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build_front:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./front
        run: npm install

      - name: Build Angular app
        working-directory: ./front
        run: npm run build

      - name: Build and tag Front Docker image
        working-directory: ./front
        run: docker build -t bobapp-front .

      - name: Save Docker image
        run: docker save bobapp-front > bobapp-front.tar

      - name: Upload Front Docker artifact
        uses: actions/upload-artifact@v4
        with:
          name: bobapp-front-image
          path: bobapp-front.tar

  build_back:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build Back-end
        working-directory: ./back
        run: mvn clean package -DskipTests

      - name: Build Back Docker image
        working-directory: ./back
        run: docker build -t bobapp-back .

      - name: Save Docker image
        run: docker save bobapp-back > bobapp-back.tar

      - name: Upload Back Docker artifact
        uses: actions/upload-artifact@v4
        with:
          name: bobapp-back-image
          path: bobapp-back.tar
